name: iara
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# This code snippet is a configuration file for a Flutter project. It specifies the project's dependencies, version number, and assets such as images and sounds. It also includes dev dependencies for testing and code generation.
dependencies:
  flutter:
    sdk: flutter

  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  cupertino_icons: ^1.0.2
  fluent_ui: ^4.8.2
  flutter_acrylic: ^1.1.3
  window_manager: ^0.3.7
  system_theme: ^2.3.1
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_svg: ^2.0.9
  mask_text_input_formatter: ^2.7.0
  socket_io_client: ^2.0.3+1
  google_fonts: ^4.0.3
  intl: ^0.18.1
  velocity_x: ^4.1.2
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2
  filepicker_windows: ^2.0.11
  windows_ui: ^0.2.0
  windows_data: ^0.2.0
  dart_console: ^1.2.0
  flutter_console: ^0.0.4
  serial_port_win32: ^1.3.0
  flutter_spinkit: ^5.2.0
  json_annotation: ^4.8.1 #Comando for build JSON : $dart run build_runner build
  bitsdojo_window:
    path: C:\Users\felip\workspace\ffsdevelopers\bitsdojo_window\bitsdojo_window

  flenex:
    path: C:\Users\felip\workspace\ffsdevelopers\flenex
  watcher: ^1.1.0
  path_provider_windows: ^2.2.1
  win32: ^5.1.1
  ninja_hex: ^2.0.1
  davi: ^3.4.1
  audioplayers: ^5.2.1
  lottie: ^2.7.0
  msix: ^3.16.7
  windows_single_instance: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  rename: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  isar_generator: 3.1.0+1

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/images/
    - assets/sounds/

msix_config:
  display_name: Confere
  publisher_display_name: FFS Developers
  identity_name: com.ffsdevelopers.confere
  msix_version: 1.0.0.2
  logo_path: E:\WorkStation\Softwares\Confere-Chiptiming\logo.png
  #capabilities: internetClient, location, microphone, webcam
  certificate_path:  E:\WorkStation\Softwares\Confere-Chiptiming\secure\CERTIFICATE.pfx
  certificate_password: fj..9283
  app_installer: #<-- app installer configuration
    publish_folder_path: E:\WorkStation\Softwares\Confere-Chiptiming\appinstaller\publish
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false