
import '../lang_constants.dart';

Map<String, String> pt_BR = {
  LangConstants.eventCode: "Código do Evento",
  LangConstants.disconnected: "Desconectado",
  LangConstants.reconnecting: "Reconectando",
  LangConstants.connecting: "Conectando",
  LangConstants.connected: "Conectado",
  LangConstants.failed: "Falha",
  LangConstants.connections : "Conexões",
  LangConstants.home : "Início",
  LangConstants.configConnection : "Configurações de Conexão",
  LangConstants.chipsToVerify: "Chips à verificar",
  LangConstants.chipsVerified: "Chips verificados",
  LangConstants.waitStart: "Aguardando inicialização",
  LangConstants.code: "Cod.",
  LangConstants.successfullyVerified: "chips foram verificados com sucesso.",
  LangConstants.waitStartInfo: "Preencha os campos acima e clique em Iniciar para iniciar a verificação dos chips.",
  LangConstants.language : "Idioma",
  LangConstants.chooseLanguage : "Escolha o idioma",
  LangConstants.english : "Inglês",
  LangConstants.portuguese : "Português",
  LangConstants.spanish : "Espanhol",
  LangConstants.theme : "Tema",
  LangConstants.chooseTheme : "Escolha o tema",
  LangConstants.light : "Claro",
  LangConstants.dark : "Escuro",
  LangConstants.status : "Status: ",
  LangConstants.type : "Tipo: ",
  LangConstants.details : "Detalhes: ",
  LangConstants.error : "Erro",
  LangConstants.eventCodeLabel: "Código do Evento",
  LangConstants.initialNumberLabel: "Número Inicial",
  LangConstants.finalNumberLabel: "Número Final",
  LangConstants.startButton: "Iniciar",
  LangConstants.resetButton: "Zerar",
  LangConstants.noReaderConnected: "Nenhum Leitor Conectado",
  LangConstants.noReaderConnectedMessage: "Atualmente, não detectamos nenhum leitor conectado ao sistema. Por favor, navegue até a aba \"Conexões\" para realizar a conexão.",
  LangConstants.goToConnections: "Ir para Conexões",
  LangConstants.eventCodeIsRequired: "Código do Evento é obrigatório",
  LangConstants.eventCodeMustBe5Digits: "Código do Evento deve ter 5 dígitos",
  LangConstants.initialNumberIsRequired: "Número Inicial é obrigatório",
  LangConstants.initialNumberMustBe5Digits: "Número Inicial deve ter 5 dígitos",
  LangConstants.finalNumberIsRequired: "Número Final é obrigatório",
  LangConstants.finalNumberMustBe5Digits: "Número Final deve ter 5 dígitos",
  LangConstants.finalNumberMustBeGreaterThanInitial: "Número Final deve ser maior que o Número Inicial",
  LangConstants.numberIsRequired: "@fieldName é obrigatório",
  LangConstants.numberMustBe5Digits: "@fieldName  deve ter 5 dígitos",

};